---
# tasks file for netzwirt.openvpn

- name: create group for open vpn
  group: 
    name: "{{openvpn_group}}"
    system: yes
    state: present


- name: create user for open vpn
  user: 
    name: "{{openvpn_user}}" 
    comment: "Open VPN"
    group: "{{openvpn_group}}"
    system: yes
    state: present
    createhome: no


- name: installing packages with apt
  import_tasks: install.apt.yml
  when: ansible_os_family == 'Debian'


- name: create openvpn directories
  file: 
    path: "{{item}}" 
    state: directory 
    mode: 0750
    owner: root
    group: "{{openvpn_group}}"
  with_items:
    - "{{ openvpn_keydir }}"
    - "{{ openvpn_configdir }}"
    - "{{ openvpn_clientconfig_dir }}"
    - "{{ openvpn_client_certificates_dir }}"

- name: copy diffie hellman params
  copy:
    src: "{{ openvpn_local_conf }}/dh{{ openvpn_key_size }}.pem"
    dest: "{{ openvpn_keydir }}/dh{{ openvpn_key_size }}.pem"
    owner: "{{ openvpn_user }}"
    group: "{{openvpn_group}}"
    mode: 644 

- name: copy CA.crt
  copy:
      src: "{{openvpn_local_conf}}/ca.crt"
      dest: "{{ openvpn_ca_cert }}"
      owner: "{{openvpn_user}}"
      group: "{{openvpn_group}}" 
      mode: 644 

- name: copy server.crt
  copy:
      src: "{{ openvpn_local_conf }}/server.crt"
      dest: "{{openvpn_server_cert}}"
      owner: "{{openvpn_user}}"
      group: "{{openvpn_group}}" 
      mode: 644 

- name: copy tls-auth key
  copy:
      src: "{{openvpn_local_conf}}/ta.key"
      dest: "{{openvpn_tls_auth_key}}"
      owner: "{{openvpn_user}}" 
      group: "{{openvpn_group}}" 
      mode: 600 
  when: openvpn_is_pki_master

- name: copy server key
  copy:
      src: "{{openvpn_local_conf}}/server.key"
      dest: "{{openvpn_server_key}}"
      owner: "{{openvpn_user}}" 
      group: "{{openvpn_group}}" 
      mode: 600 
  when: openvpn_is_pki_master

- name: copy client certificates
  copy:
      src: "{{openvpn_local_conf}}/clients"
      dest: "{{ openvpn_configdir }}"
      owner: "{{openvpn_user}}"
      group: "{{openvpn_group}}" 
      mode: 640 


- name: create openvpn server config
  template:
    dest: "{{openvpn_configdir}}/server.conf"
    src: server.conf.j2
  notify: 
  - openvpn restart


- name: Ensure OpenVPN is started
  service: 
    name: openvpn 
    state: started 
    enabled: yes


- import_tasks: client.configs.yml



# - name: create clientconfig (ccd)
#   template:
#     src: ccd.tpl.j2
#     dest: "{{openvpn_clientconfig_dir}}/{{ item.fullname }} <{{ item.email }}>"
#   with_items: "{{  openvpn_users  }}"
#   when: item.ip_addr is defined
